export const USER_SET_AUTH = 'USER_SET_AUTH';
export const USER_SET_PICTURE = 'USER_SET_PICTURE';

export const APPLICATIONS_SET_APPLICATIONS = 'APPLICATIONS_SET_APPLICATIONS';

export const POSTINGS_SET_POSTINGS = 'POSTINGS_SET_POSTINGS';
export const POSTINGS_SET_POSTING_BY_ID = 'POSTINGS_SET_POSTING_BY_ID';

export const TEAMS_SET_TEAMS = 'TEAMS_SET_TEAMS';
export const TEAMS_SET_TEAM_DESC = 'TEAMS_SET_TEAM_DESC';
