// EXTERNAL:
export const USER_SET_AUTH = 'USER_SET_AUTH';
export const USER_SET_PICTURE = 'USER_SET_PICTURE';
export const USER_SET_PROFILE = 'USER_SET_PROFILE';

// DASHBOARD:
export const APPLICATIONS_SET_APPLICATIONS = 'APPLICATIONS_SET_APPLICATIONS';
export const APPLICATIONS_SET_APPLICATIONS_BY_EMAIL =
  'APPLICATIONS_SET_APPLICATIONS_BY_EMAIL';
export const APPLICATIONS_SET_APPLICATION_STATUSES =
  'APPLICATIONS_SET_APPLICATION_STATUSES';
export const APPLICATIONS_UPDATE_APP_STATUS = 'APPLICATIONS_UPDATE_APP_STATUS';

export const INTERVIEWS_SET_INTERVIEWS = 'INTERVIEWS_SET_INTERVIEWS';
export const INTERVIEWS_SET_INTERVIEW_BY_ID = 'INTERVIEWS_SET_INTERVIEW_BY_ID';
export const INTERVIEWS_UPDATE_INTERVIEW_NOTE =
  'INTERVIEWS_UPDATE_INTERVIEW_NOTE';

export const EMAIL_SET_DATA = 'EMAIL_SET_DATA';

export const CONFIGURATION_SET_CONFIGURATION =
  'CONFIGURATION_SET_CONFIGURATION';

// CMS:
export const POSTINGS_SET_POSTINGS = 'POSTINGS_SET_POSTINGS';
export const POSTINGS_SET_POSTING_BY_ID = 'POSTINGS_SET_POSTING_BY_ID';

export const TEAMS_SET_TEAMS = 'TEAMS_SET_TEAMS';
export const TEAMS_SET_TEAM_DESC = 'TEAMS_SET_TEAM_DESC';
